#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers

obj-$(CONFIG_SENSORS_KXTJ9)     += kxtj9/
obj-$(CONFIG_SENSORS_AK09911)   += akm09911/
obj-$(CONFIG_HALL_SENSOR)       += hall/
obj-$(CONFIG_SENSORS_AK09911_a600cg)   += akm09911_a600cg/
