ccflags-y += -DATOMISP_POSTFIX=\"css2401a0_legacy_v21\" -DATOMISP_FWNAME=\"shisp_2401a0_legacy_v21.bin\" -DISP2401 -DCSS20 -DCSS21
CSS20 := m
CSS21 := m
ISP2401 := y
postfix := css2401a0_legacy_v21

include $(srctree)/$(src)/../Makefile.common
